### ISSUE TITLE
Potential Confusion In The Issue Tracker

### ISSUE THREAD

**Issue by jeffscottbrown** [graceframework/grace-framework#270] opened 2024-04-08 16:17 UTC
### Issue description

The issue templates currently deployed at https://github.com/graceframework/grace-framework/issues are going to create some confusion in the community.  Just as an example, choosing between issue types at https://github.com/graceframework/grace-framework/issues/new/choose if I attempt to submit a new Feature request, the page says the following:

> Please describe the feature you want for Grails® framework to implement, before that check if there is already an existing issue to add it.

I think it would be good if Grace introduced more clarity around  its relationship to Grails so folks don't think that is a place to submit Grails feature requests.  I think the feature request template that Grace is using is misleading in its current state.

**Comment by rainboyan** [comment] 2024-04-08 18:23
@osscontributor Thank you for your suggestion, I've updated the issue templates, I'm sorry for the misunderstanding caused by my negligence. I'm closing this for now, feel free to open it if you have any questions.

**Closed as completed** 2024-04-08 18:24 UTC
